include=/home/adi/.cache/wal/colors-fuzzel.ini

# options
font=Space Grotesk:size=12
dpi-aware=auto
prompt="> "
password-character=*
show-actions=no
terminal=ghostty
list-executables-in-path=no
exit-on-keyboard-focus-loss=no
layer=overlay

# icons
icon-theme=Fluent-dark
icons-enabled=yes

# style
lines=5
width=30
tabs=8
horizontal-pad=24
vertical-pad=20
inner-pad=16

[border]
width=0
radius=10

# [colors]
# background=100F0FFF
# border=24837BFF
# input=CECDC3FF
# match=24837BFF
# placeholder=878580FF
# prompt=CECDC3FF
# selection-match=A02F6FFF
# selection-text=24837Bff
# selection=100F0FFF
# text=CECDC3FF
